# Generated by Django 4.2

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_add_sections_subsections"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quizzes", "0003_practicesession_chatsession_chatmessage_chatfile"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentAdaptivePolicyState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("q_table", models.JSONField(default=dict)),
                ("bandit", models.JSONField(default=dict)),
                ("lin_weights", models.JSONField(default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adaptive_practice_policies",
                        to="courses.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adaptive_practice_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "course")},
            },
        ),
    ]
