# Generated by Django 4.2.7 on 2026-05-04 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_studentadaptivepolicystate_ability_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentadaptivepolicystate',
            name='ability_state',
            field=models.JSONField(default=dict, help_text='IRT-lite θ, per-topic accuracy, stratum stats for hybrid policy.'),
        ),
    ]
