# Generated by Django 4.2.7 on 2025-12-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_file',
            field=models.FileField(blank=True, null=True, upload_to='assignment_files/'),
        ),
    ]
