# Generated by Django 4.2.7 on 2026-02-26 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0002_assignment_assignment_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="assignment_file",
        ),
    ]
