# Generated by Django 4.2.7 on 2026-03-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0003_remove_assignment_assignment_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="instruction_file",
            field=models.FileField(
                blank=True, null=True, upload_to="assignment_instructions/"
            ),
        ),
    ]
